version: "3.7"
services:
  frontend:
    image: nginx
    container_name: my-nginx
    ports:
      - 80:80
    volumes:
      - nginx-logs:/var/logs/nginx
    networks:
      - nginx-bridge
networks:
  nginx-bridge:
    driver: bridge
volumes:
  nginx-logs:
    driver: local
